project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!guidance/SOP.md"

website:
  title: South East Outpatient Activity Dashboard Userguide

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    respect-user-color-scheme: true
    toc: true
    toc-depth: 4
    toc-location: left
    toc-float: true
    page-layout: full
    number-sections: true