project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!guidance/SOP.md"

website:
  title: South East Outpatient Activity Dashboard Userguide
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: measures.qmd
        text: Measures
      - href: pages.qmd
        text: Pages
      - href: glossary.qmd
        text: Glossary
format:
  html:
    theme:
      light: [cosmo, custom_light.scss]
      dark: darkly
    respect-user-color-scheme: true
    toc: true
    toc-depth: 4
    toc-location: right
    toc-float: true
    page-layout: full
    number-sections: true